"""Port: repositório de clientes do assessor."""

from __future__ import annotations

from typing import Protocol

from src.assistente.domain.entities.cliente_assessor import ClienteAssessor


class ClienteAssessorRepository(Protocol):
    async def salvar(self, cliente: ClienteAssessor) -> None: ...
    async def salvar_todos(self, clientes: list[ClienteAssessor]) -> int: ...
    async def buscar_por_codigo(self, codigo_conta: str) -> ClienteAssessor | None: ...
    async def buscar_por_nome(self, nome: str) -> list[ClienteAssessor]: ...
    async def listar_todos(self) -> list[ClienteAssessor]: ...
    async def total(self) -> int: ...
