"""Port: repositório de eventos."""

from __future__ import annotations

from datetime import date
from typing import Protocol

from src.assistente.domain.entities.evento import Evento


class EventoRepository(Protocol):
    async def salvar(self, evento: Evento) -> None: ...
    async def buscar_por_id(self, id: str) -> Evento | None: ...
    async def listar_para_alertar(self, hoje: date) -> list[Evento]: ...
    async def listar_por_conta(self, codigo_conta: str) -> list[Evento]: ...
    async def listar_proximos(self, dias: int = 7) -> list[Evento]: ...
    async def marcar_alertado(self, id: str) -> None: ...
    async def marcar_concluido(self, id: str) -> None: ...
