"""Port: repositório de posições de renda fixa."""

from __future__ import annotations

from datetime import date
from typing import Protocol

from src.assistente.domain.entities.renda_fixa import RendaFixa


class RendaFixaRepository(Protocol):
    async def salvar_todos(self, posicoes: list[RendaFixa]) -> int: ...
    async def listar_por_conta(self, codigo_conta: str) -> list[RendaFixa]: ...
    async def listar_vencendo_em(self, dias: int) -> list[RendaFixa]: ...
    async def marcar_evento_criado(self, ids: list[str]) -> None: ...
    async def deletar_todos(self) -> int: ...
    async def total(self) -> int: ...
