"""Port: repositório de reuniões."""

from __future__ import annotations

from datetime import date
from typing import Protocol

from src.assistente.domain.entities.reuniao import Reuniao


class ReuniaoRepository(Protocol):
    async def salvar(self, reuniao: Reuniao) -> None: ...
    async def buscar_por_id(self, id: str) -> Reuniao | None: ...
    async def listar_do_dia(self, data: date) -> list[Reuniao]: ...
    async def listar_por_conta(self, codigo_conta: str) -> list[Reuniao]: ...
    async def listar_proximas(self, dias: int = 7) -> list[Reuniao]: ...
    async def marcar_relatorio_gerado(self, id: str) -> None: ...
    async def atualizar_outlook_id(self, id: str, outlook_event_id: str) -> None: ...
